### ISSUE TITLE
How do I patch

### ISSUE THREAD

**Issue by shord89** [hawkfalcon/Timberborn-Mods#3]
I have figured out where the coding goes within the frame work but can not figure out how to update with the new commands. How would I succesfully patch this?

**Comment by Rage404** [comment]
Getting this "updated" version here also has me stuck on how to use/install/patch it

**Comment by Heckler86** [comment]
It looks to me that the author has patched his mod, but did not create a *.dll file for it.
From what I can tell they fixed the UnifiedFactions.cs file for the experimental branch.

But there has not been an upload of the needed Unified Factions.dll file neither here on github, nor in the thunderstore.io portal.

So basically what we need is for someone to create the Unified Factions.dll (I think its done via MS Visual Studio) from the 3 existing project files which are uploaded here on github. Namely: UnifiedFactions.cs UnifiedFactions.csproj UnifiedFactions.sln

Sadly I am not familiar with Visual Studio and vreating .dll files so I can not do it.

Maybe someone else can do it or the author will upload an up to date version of their mod to the thunderstore.io portal.

I will not play Timberborn until there is an update, since in my opinion the option of playing with all faction buildings should be part of the base game. :)

**Comment by hawkfalcon** [comment]
Here you go. I just didn't want to upload it to thunderstore because some people use experimental branch and some people use stable branch.

https://github.com/hawkfalcon/Timberborn-Mods/releases/tag/Experimental

**Comment by Heckler86** [comment]
Thank you very much!
Your mod really makes the game worth playing for me.

**Comment by shord89** [comment]
We really appreciate it! I wanted it bad enough I've been looking into how to turn your files into a .dll I was curious would you mind walking me through how you fixed it. I am now trying to learn more about modding so I can make my own mods. I know a little about coding, but very easily can learn new skills. Either way I am looking forward to using this mod for the first time ever!

**Comment by hawkfalcon** [comment]
Sure! Please join the discord
